import type { Metadata } from 'next';
import { ArrowUpRight } from 'lucide-react';
import { BRAND, HOTELS, PROPERTIES, waLink } from '@/data/innzoyData';
import EditorialImage from '@/components/common/EditorialImage';
import { BookingTrigger } from '@/components/booking/BookingProvider';

export const metadata: Metadata = {
  title: 'Contact — Innzoy Hotels & Guest Houses',
  description: 'Reach the Innzoy front desks on WhatsApp, or contact the head office in Kondapur, Hyderabad for corporate bookings.',
};
export default function ContactPage() {
  return <article className="open-contact open-page">
    <header className="open-contact-opening"><div className="open-contact-intro"><p className="open-eyebrow">Contact / Innzoy Hyderabad</p><h1>Say hello.</h1><p>Message any front desk on WhatsApp for availability and rates, or reach the head office for corporate bookings and invoicing.</p><a href={`tel:${BRAND.contact.phone.replace(/\s/g, '')}`} className="open-contact-main-phone">{BRAND.contact.phone}<ArrowUpRight size={20} aria-hidden="true" /></a><a href={`mailto:${BRAND.contact.email}`} className="open-action">{BRAND.contact.email}<ArrowUpRight size={16} aria-hidden="true" /></a></div><figure className="open-contact-photo"><EditorialImage src={HOTELS[1].gallery[2]} alt="The reception at Innzoy DLF Road" fill preload sizes="(max-width: 760px) 100vw, 42vw" containerClassName="open-photo-fill" revealType="curtain-h" delay={0} /><figcaption>DLF Road / Reception</figcaption></figure></header>
    <section className="open-contact-desks" aria-labelledby="front-desks-title"><div className="open-section-heading"><div><p className="open-eyebrow">Direct connections</p><h2 id="front-desks-title">Front desks.</h2></div><p>WhatsApp / Availability &amp; rates</p></div><div className="open-desk-index">{BRAND.desks.map((desk, index) => <a key={desk.name} href={waLink(desk.whatsapp, 'Hello, I got the contact number from your website. I would like to know about availability at Innzoy ' + desk.name + '.')} target="_blank" rel="noopener noreferrer" className="open-desk" aria-label={`Message ${desk.name} front desk on WhatsApp, ${desk.phone}`}><span className="open-eyebrow">{String(index + 1).padStart(2, '0')}</span><h3>{desk.name}</h3><span>{desk.phone}</span><span className="open-desk-action">Message desk <ArrowUpRight size={18} aria-hidden="true" /></span></a>)}</div></section>
    <section className="open-contact-office" aria-labelledby="contact-office-title"><div><p className="open-eyebrow">Corporate enquiries</p><h2 id="contact-office-title">Head office.</h2></div><address>{BRAND.contact.headOffice}</address><div><a href={`tel:${BRAND.contact.phone.replace(/\s/g, '')}`} className="open-action">{BRAND.contact.phone}</a><a href={`mailto:${BRAND.contact.email}`} className="open-action">{BRAND.contact.email}</a><BookingTrigger intent="corporate" className="open-action">Corporate booking <ArrowUpRight size={17} aria-hidden="true" /></BookingTrigger></div></section>
    <section className="open-contact-addresses" aria-labelledby="addresses-title"><div className="open-section-heading"><div><p className="open-eyebrow">Find your way</p><h2 id="addresses-title">All addresses.</h2></div><p>{String(PROPERTIES.length).padStart(2, '0')} locations / Hyderabad</p></div><ol>{PROPERTIES.map((property, index) => <li key={property.id}><span className="open-eyebrow">{String(index + 1).padStart(2, '0')}</span><div><p className="open-eyebrow">{property.label}</p><h3>{property.name}</h3><address>{property.address}</address></div><a href={property.mapUrl} target="_blank" rel="noopener noreferrer" className="open-action" aria-label={`Open map for Innzoy ${property.name}`}>Map <ArrowUpRight size={16} aria-hidden="true" /></a></li>)}</ol></section>
  </article>;
}
